return {
  "ibhagwan/fzf-lua",
  dependencies = { "nvim-mini/mini.icons" },
  opts = {},
  keys= {
    -- Open, Find, Search
    { "<leader><leader>",
      function() require('fzf-lua').buffers() end,
      desc="Find existing buffers",
    },
    { "<leader>/",
      function() require('fzf-lua').lgrep_curbuf() end,
      desc="Live grep the current buffer",
    },
    { "<leader>..",
      function() require('fzf-lua').files() end,
      desc="Find files in the current project",
    },
    { "<leader>.g",
      function() require('fzf-lua').live_grep() end,
      desc="Live grep in the current project",
    },
    { "<leader>.c",
      function() require('fzf-lua').files({cwd=vim.fn.stdpath("config")}) end,
      desc="Find in neovim configuration",
    },
    { "<leader>.z",
      function() require('fzf-lua').builtin() end,
      desc="Find fzf builtin functions",
    },
    { "<leader>.k",
      function() require('fzf-lua').keymaps() end,
      desc="Find keymapping",
    },
    { "<leader>.h",
      function() require('fzf-lua').helptags() end,
      desc="Find helptags",
    },
    -- LSP
    { ",D",
      function() require('fzf-lua').diagnostics_document() end,
      desc="LSP: Diagnostics",
    },
    { ",r",
      function() require('fzf-lua').lsp_references() end,
      desc="LSP: References",
    },
    { ",d",
      function() require('fzf-lua').lsp_definitions() end,
      desc="LSP: Definitions",
    }
  },
}
